package m6group6.project1.model;

import jakarta.persistence.*;           // JPA annotations (Jakarta)
import jakarta.validation.constraints.*; // Bean Validation (optional but recommended)

@Entity
@Table(name = "users") // matches the actual table name
public class UserEntity {

    // Recommend using Integer (nullable) instead of primitive int to represent "not persisted yet"
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // PostgreSQL identity column
    @Column(name = "user_id", updatable = false, nullable = false)
    private Integer userId;

    @NotBlank(message = "Name is required")
    @Size(max = 200, message = "Name must be at most 200 characters")
    @Column(name = "name", nullable = false, length = 200)
    private String name;

    public UserEntity() {}

    public UserEntity(String name) {
        // do not set ID here; it is generated by the database
        this.name = (name == null ? null : name.trim());
    }

    // --- getters/setters ---
    public Integer getUserID() {
        return userId;
    }

    public void setUserID(Integer userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = (name == null ? null : name.trim());
    }

}